# Data Preparation

In [4]:
pip install torch

Requirement already satisfied: torch in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (2.12.1)
Requirement already satisfied: filelock in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (3.29.4)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from torch) (2026.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nitro v15\anaconda3\envs\nlp\lib\site-packages (from jinja2->torch) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import torch

print(f"Apakah CUDA tersedia? {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Nama GPU: {torch.cuda.get_device_name(0)}")
    print(f"Jumlah GPU: {torch.cuda.device_count()}")
else:
    print("PyTorch tidak mendeteksi GPU. Pastikan driver dan PyTorch CUDA sudah terinstal.")

Apakah CUDA tersedia? False
PyTorch tidak mendeteksi GPU. Pastikan driver dan PyTorch CUDA sudah terinstal.

In [6]:
import pandas as pd

df=pd.read_csv('Reviews.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'Reviews.csv'

In [ ]:
df['Text'][0]

'I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.'

In [ ]:
df = df[df['Score'] != 3].copy()
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...,...,...
568449,568450,B001EO7N10,A28KG5XORO54AY,Lettie D. Carter,0,0,5,1299628800,Will not do without,Great for sesame chicken..this is a good if no...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,R. Sawyer,0,0,2,1331251200,disappointed,I'm disappointed with the flavor. The chocolat...
568451,568452,B004I613EE,A121AA1GQV751Z,"pksd ""pk_007""",2,2,5,1329782400,Perfect for our maltipoo,"These stars are small, so you can give 10-15 o..."
568452,568453,B004I613EE,A3IBEVCTXKNOH,"Kathy A. Welch ""katwel""",1,1,5,1331596800,Favorite Training and reward treat,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,srfell17,0,0,5,1338422400,Great Honey,"I am very satisfied ,product is as advertised,..."

In [ ]:
score_map={
    1:'Negative',
    2:'Negative',
    4:'Positive',
    5:'Positive'
}

df['Score']=df['Score'].map(score_map)
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,Positive,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,Negative,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,Positive,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,Negative,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,Positive,1350777600,Great taffy,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...,...,...
568449,568450,B001EO7N10,A28KG5XORO54AY,Lettie D. Carter,0,0,Positive,1299628800,Will not do without,Great for sesame chicken..this is a good if no...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,R. Sawyer,0,0,Negative,1331251200,disappointed,I'm disappointed with the flavor. The chocolat...
568451,568452,B004I613EE,A121AA1GQV751Z,"pksd ""pk_007""",2,2,Positive,1329782400,Perfect for our maltipoo,"These stars are small, so you can give 10-15 o..."
568452,568453,B004I613EE,A3IBEVCTXKNOH,"Kathy A. Welch ""katwel""",1,1,Positive,1331596800,Favorite Training and reward treat,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,srfell17,0,0,Positive,1338422400,Great Honey,"I am very satisfied ,product is as advertised,..."

In [ ]:
df=df[['Score','Text']]
df

           Score                                               Text
0       Positive  I have bought several of the Vitality canned d...
1       Negative  Product arrived labeled as Jumbo Salted Peanut...
2       Positive  This is a confection that has been around a fe...
3       Negative  If you are looking for the secret ingredient i...
4       Positive  Great taffy at a great price.  There was a wid...
...          ...                                                ...
568449  Positive  Great for sesame chicken..this is a good if no...
568450  Negative  I'm disappointed with the flavor. The chocolat...
568451  Positive  These stars are small, so you can give 10-15 o...
568452  Positive  These are the BEST treats for training and rew...
568453  Positive  I am very satisfied ,product is as advertised,...

[525814 rows x 2 columns]

In [ ]:
df['Score'].value_counts()

Score
Positive    443777
Negative     82037
Name: count, dtype: int64

In [ ]:
df_positive = df[df['Score'] == 'Positive']
df_negative = df[df['Score'] == 'Negative']

df_positive = df_positive.sample(n=50000, random_state=42)
df_negative = df_negative.sample(n=50000, random_state=42)

df_sample = pd.concat([df_positive, df_negative])

df_sample = df_sample.sample(frac=1, random_state=42).reset_index(drop=True)

print("Jumlah data setelah di-balance:")
print(df_sample['Score'].value_counts())

Jumlah data setelah di-balance:
Score
Negative    50000
Positive    50000
Name: count, dtype: int64

In [ ]:
df_sample

          Score                                               Text
0      Negative  I was expecting a lot more from this coffee. I...
1      Negative  POD is a generic word, and nothing in the desc...
2      Positive  I recently purchased the Kerig coffee maker, a...
3      Negative  I'm just going to say it: These CHIPS Taste li...
4      Negative  This bread is very dry and crumbly compared to...
...         ...                                                ...
99995  Positive  illy issimo is Coca Cola's attempt to break in...
99996  Negative  Before you think all the '1-star' people are j...
99997  Negative  This review will make me sound really stupid, ...
99998  Positive  I've tried several of the MiO flavors now, and...
99999  Positive  I eat this muesli every morning for breakfast ...

[100000 rows x 2 columns]

# Data Preprocessing

In [ ]:
import re
import contractions

In [ ]:
def preprocessing(text):
    if type(text) != str:
        return ""
    
    text = text.lower()
    
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'www\.\S+', '', text)
    
    text = contractions.fix(text)
    
    text = " ".join(text.split())
    
    return text

In [ ]:
from tqdm import tqdm
tqdm.pandas()

df_clean=df_sample.copy()
df_clean['Text']=df_sample['Text'].progress_apply(preprocessing)
df_clean

100%|██████████| 100000/100000 [00:04<00:00, 21763.93it/s]

          Score                                               Text
0      Negative  i was expecting a lot more from this coffee. i...
1      Negative  pod is a generic word, and nothing in the desc...
2      Positive  i recently purchased the kerig coffee maker, a...
3      Negative  i am just going to say it: these chips taste l...
4      Negative  this bread is very dry and crumbly compared to...
...         ...                                                ...
99995  Positive  illy issimo is coca cola's attempt to break in...
99996  Negative  before you think all the '1-star' people are j...
99997  Negative  this review will make me sound really stupid, ...
99998  Positive  i have tried several of the mio flavors now, a...
99999  Positive  i eat this muesli every morning for breakfast ...

[100000 rows x 2 columns]

In [ ]:
mapping={
    'Positive':1,
    'Negative':0
}

df_clean['Score']=df_clean['Score'].map(mapping)
df_clean

       Score                                               Text
0          0  i was expecting a lot more from this coffee. i...
1          0  pod is a generic word, and nothing in the desc...
2          1  i recently purchased the kerig coffee maker, a...
3          0  i am just going to say it: these chips taste l...
4          0  this bread is very dry and crumbly compared to...
...      ...                                                ...
99995      1  illy issimo is coca cola's attempt to break in...
99996      0  before you think all the '1-star' people are j...
99997      0  this review will make me sound really stupid, ...
99998      1  i have tried several of the mio flavors now, a...
99999      1  i eat this muesli every morning for breakfast ...

[100000 rows x 2 columns]

# Split

In [ ]:
from sklearn.model_selection import train_test_split

text=df_clean['Text'].tolist()
score=df_clean['Score'].tolist()
train_text,test_text,train_score,test_score=train_test_split(text,score,test_size=0.2,stratify=score)

# Hugging Face Tokenization

In [ ]:
from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained('distilbert-base-uncased')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
def tokenize(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=128
    )

In [ ]:
train_dict={
    'text':train_text,
    'label':train_score
}
test_dict={
    'text':test_text,
    'label':test_score
}

In [ ]:
from datasets import Dataset

train_dataset=Dataset.from_dict(train_dict)
test_dataset=Dataset.from_dict(test_dict)

In [ ]:
tokenized_train=train_dataset.map(tokenize,batched=True)
tokenized_test=test_dataset.map(tokenize,batched=True)

Map:   0%|          | 0/80000 [00:00<?, ? examples/s]

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

# Training

In [ ]:
import evaluate
import numpy as np

metric=evaluate.load('accuracy')

def compute_metrics(eval_pred):
    logits,labels=eval_pred
    pred=np.argmax(logits,axis=-1)
    return metric.compute(predictions=pred,references=labels)

In [ ]:
from transformers import AutoModelForSequenceClassification

model=AutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased',num_labels=2)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import TrainingArguments

training_args=TrainingArguments(
    output_dir='./model_new',
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True
)

In [ ]:
from transformers import Trainer

trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    compute_metrics=compute_metrics
)
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

TrainOutput(global_step=15000, training_loss=0.12061245613098144, metrics={'train_runtime': 2954.5841, 'train_samples_per_second': 81.23, 'train_steps_per_second': 5.077, 'total_flos': 7948043919360000.0, 'train_loss': 0.12061245613098144, 'epoch': 3.0})

# Testing

In [ ]:
import pandas as pd
import re
import contractions

def preprocessing(text):
    if type(text) != str:
        return ""
    
    text = text.lower()
    
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'www\.\S+', '', text)
    
    text = contractions.fix(text)
    
    text = " ".join(text.split())
    
    return text

In [ ]:
from transformers import pipeline

sentiment=pipeline(
    'text-classification',
    model='./model_new/checkpoint-10000',
    tokenizer='distilbert-base-uncased'
)

test = [
    "The food was absolutely delicious and the delivery was fast!",
    "I will never buy this product again. It tastes like garbage and the box was broken."
]

label_map={
    'LABEL_1':'Positive',
    'LABEL_0':'Negative'
}

predict=sentiment(test)
for text,pred in zip(test,predict):
    label=label_map.get(pred['label'],pred['label'])
    print(f'Teks: {text}')
    print(f"Prediksi: {label} (Accuracy: {pred['score']})\n")

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Teks: The food was absolutely delicious and the delivery was fast!
Prediksi: Positive (Accuracy: 0.9994603991508484)

Teks: I will never buy this product again. It tastes like garbage and the box was broken.
Prediksi: Negative (Accuracy: 0.9993933439254761)

# Output

In [ ]:
import spacy
nlp=spacy.load('en_core_web_sm')

In [ ]:
def output(text):
    clean_text = preprocessing(text)
    doc = nlp(clean_text)
    hasil_ekstraksi = []

    for token in doc:
        # ======================================================
        # SKENARIO 1 & 2: Opini berupa Kata Sifat (ADJ)
        # ======================================================
        if token.pos_ == "ADJ":
            aspect = None
            opinion = token.text
            verb_context = "" 
            intensifier = "" 
            
            for child in token.children:
                if child.dep_ == "advmod":
                    intensifier = child.text + " "
            
            if token.dep_ == "amod" and token.head.pos_ == "NOUN":
                aspect = token.head.text
                
            elif token.dep_ == "acomp" and token.head.pos_ in ["AUX", "VERB"]:
                for child in token.head.children:
                    if child.dep_ == "nsubj" and child.pos_ == "NOUN":
                        aspect = child.text
                        break
            
            if aspect:
                for ancestor in token.ancestors:
                    if ancestor.pos_ == "VERB":
                        verb = ancestor.text
                        subj = ""
                        verb_neg = ""
                        for child in ancestor.children:
                            if child.dep_ in ["nsubj", "nsubjpass", "PRON"]:
                                subj = child.text + " "
                            if child.dep_ == "neg":
                                verb_neg = child.text + " "
                        verb_context = f"{subj}{verb_neg}{verb} "
                        break 
        
            if aspect and opinion:
                negation = ""
                for child in token.children:
                    if child.dep_ == "neg":
                        negation = child.text + " "
                if token.head.pos_ in ["AUX", "VERB"]:
                    for child in token.head.children:
                        if child.dep_ == "neg":
                            negation = child.text + " "

                opini_lengkap = f"{negation}{intensifier}{opinion}".strip()
                
                if verb_context:
                    kalimat_fokus = f"{verb_context}the {aspect} is {opini_lengkap}"
                else:
                    kalimat_fokus = f"The {aspect} is {opini_lengkap}"
                
                kalimat_fokus = " ".join(kalimat_fokus.split())
                
                prediksi_sentimen = sentiment(kalimat_fokus)[0]
                label = "Positif" if prediksi_sentimen['label'] == 'LABEL_1' else "Negatif"
                skor = f"{prediksi_sentimen['score'] * 100:.1f}%"
                
                hasil_ekstraksi.append({
                    "Aspek": aspect.capitalize(),
                    "Opini Pengguna": opini_lengkap.lower(),
                    "Kalimat Evaluasi": kalimat_fokus, 
                    "Sentimen": label,
                    "Tingkat Keyakinan": skor
                })

        # ======================================================
        # SKENARIO 3 (BARU): Opini berupa Kata Kerja (VERB)
        # Contoh kalimat: "I love the cake and coffee and bread"
        # ======================================================
        elif token.pos_ == "VERB":
            opinion = token.text
            
            # Cek negasi (misal: "don't love")
            negation = ""
            for child in token.children:
                if child.dep_ == "neg":
                    negation = child.text + " "
                    
            # Cari subjek yang melakukan kata kerja
            subj = ""
            for child in token.children:
                if child.dep_ in ["nsubj", "PRON"]:
                    subj = child.text + " "
                    
            # Cari objek utama makanan yang dikenai kata kerja (dobj)
            for child in token.children:
                if child.dep_ == "dobj" and child.pos_ == "NOUN":
                    # Makanan pertama ditemukan (contoh: "cake")
                    daftar_makanan = [child]
                    
                    # MAGIS SPACY: Menangkap makanan lain yang dirangkai dengan "and"
                    for conj in child.conjuncts:
                        if conj.pos_ == "NOUN":
                            daftar_makanan.append(conj)
                            
                    # Proses seluruh makanan yang ditemukan
                    for makanan_token in daftar_makanan:
                        aspect = makanan_token.text
                        
                        # Rakit kalimat, contoh hasil: "i love the cake"
                        kalimat_fokus = f"{subj}{negation}{opinion} the {aspect}"
                        kalimat_fokus = " ".join(kalimat_fokus.split())
                        
                        prediksi_sentimen = sentiment(kalimat_fokus)[0]
                        label = "Positif" if prediksi_sentimen['label'] == 'LABEL_1' else "Negatif"
                        skor = f"{prediksi_sentimen['score'] * 100:.1f}%"
                        
                        hasil_ekstraksi.append({
                            "Aspek": aspect.capitalize(),
                            "Opini Pengguna": f"{negation}{opinion}".strip().lower(),
                            "Kalimat Evaluasi": kalimat_fokus,
                            "Sentimen": label,
                            "Tingkat Keyakinan": skor
                        })
                    break # Berhenti mencari jika objek sudah ketemu

    if not hasil_ekstraksi:
        return pd.DataFrame([{"Pesan": "Tidak ada aspek dan opini yang berhasil diekstrak dari kalimat."}])
    
    return pd.DataFrame(hasil_ekstraksi)

In [ ]:
# ==========================================
# Uji Coba Output Terstruktur
# ==========================================
ulasan_user = "Overall, Emilia Cucina Italiana is a wonderful place not only for great food, but also for outstanding hospitality and special moments. I would highly recommend it and would be happy to return."
df_hasil = output(ulasan_user)

# Jika dijalankan di VS Code/Jupyter, ini akan mencetak tabel yang sangat rapi
display(df_hasil)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

,Aspek,Opini Pengguna,Kalimat Evaluasi,Sentimen,Tingkat Keyakinan
0,Place,wonderful,The place is wonderful,Positif,99.8%
1,Food,great,The food is great,Positif,99.8%
2,Hospitality,outstanding,The hospitality is outstanding,Positif,99.7%
3,Moments,special,The moments is special,Positif,94.5%